const asset = ({
  key,
  url,
  title,
  subtitle,
  assetId,
  version,
  updated,
  filename,
  pages,
  mode,
  quality,
  kind = "pdf",
}) => ({
  key,
  url,
  title,
  subtitle,
  assetId,
  version,
  updated,
  filename,
  pages,
  mode,
  quality,
  kind,
  metaLine: [assetId, version, updated].filter(Boolean).join(" · "),
});

const downloads = {
  notfallkarte: asset({
    key: "notfallkarte",
    url: "/downloads/notfallkarte-kanton-zuerich-puk.pdf",
    title: "Notfallkarte Kanton Zürich",
    subtitle: "Krisen-Handout mit 144, 117 und Ärztefon-Triage",
    assetId: "DL-01",
    version: "core_v02",
    updated: "2026-05-14",
    filename: "notfallkarte-kanton-zuerich-puk.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  krisenplanVorlage: asset({
    key: "krisenplanVorlage",
    url: "/downloads/krisenplan-vorlage-bipolare-stoerung-puk-zuerich.pdf",
    title: "Krisenplan-Vorlage – Bipolare Störung",
    subtitle: "Vorlage zum Ausfüllen für stabile Phasen",
    assetId: "DL-02",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "krisenplan-vorlage-bipolare-stoerung-puk-zuerich.pdf",
    pages: "PDF · 2 Seiten A4 · ausfüllbar",
    mode: "download",
    quality: "core",
  }),
  kurzblattStabilisiert: asset({
    key: "kurzblattStabilisiert",
    url: "/downloads/kurzblatt-was-stabilisiert-was-schadet-puk-zuerich.pdf",
    title: "Was stabilisiert - was schadet",
    subtitle: "Kompaktes Blatt für Kommunikation, Selbstfürsorge und Grenzen",
    assetId: "DL-03",
    version: "core_v01",
    updated: "2026-05-13",
    filename: "kurzblatt-was-stabilisiert-was-schadet-puk-zuerich.pdf",
    pages: "PDF · 2 Seiten A4",
    mode: "download",
    quality: "core",
  }),
  // ── Acute situation reference set (promoted from handout-drafts 22.4.2026) ──
  suizidgedanken: asset({
    key: "suizidgedanken",
    url: "/downloads/umgang-mit-suizidgedanken-puk-zuerich.pdf",
    title: "Umgang mit Suizidgedanken",
    subtitle: "Ansprechen rettet Leben",
    assetId: "DL-04",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "umgang-mit-suizidgedanken-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  psychoseWahn: asset({
    key: "psychoseWahn",
    url: "/downloads/umgang-mit-psychose-wahn-puk-zuerich.pdf",
    title: "Psychose / Wahn",
    subtitle: "Was hilft, wenn Kontakt und Realität entgleiten",
    assetId: "DL-05",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "umgang-mit-psychose-wahn-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  manie: asset({
    key: "manie",
    url: "/downloads/umgang-mit-manie-puk-zuerich.pdf",
    title: "Umgang mit Manie",
    subtitle: "Praktische Strategien in manischen Phasen",
    assetId: "DL-06",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "umgang-mit-manie-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  depression: asset({
    key: "depression",
    url: "/downloads/umgang-mit-depression-puk-zuerich.pdf",
    title: "Umgang mit Depression",
    subtitle: "Wenn die erkrankte Person nicht erreichbar ist",
    assetId: "DL-07",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "umgang-mit-depression-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  // ── Welle-8-Promotion 23.4.2026: b3 + rechtliche Orientierung ──
  kritischeZeitpunkte: asset({
    key: "kritischeZeitpunkte",
    url: "/downloads/kritische-zeitpunkte-angehoerige-puk-zuerich.pdf",
    title: "Kritische Zeitpunkte",
    subtitle: "Belastende Übergänge und Nachwirkungen früher erkennen",
    assetId: "DL-11",
    version: "core_v02",
    updated: "2026-05-12",
    filename: "kritische-zeitpunkte-angehoerige-puk-zuerich.pdf",
    pages: "PDF · 2 Seiten A4",
    mode: "download",
    quality: "core",
  }),
  rechtlicheOrientierung: asset({
    key: "rechtlicheOrientierung",
    url: "/downloads/rechtliche-orientierung-angehoerige-puk-zuerich.pdf",
    title: "Rechtliche Orientierung",
    subtitle: "Schweigepflicht, Vorsorge und Systemfragen praktisch ordnen",
    assetId: "DL-12",
    version: "core_v02",
    updated: "2026-05-13",
    filename: "rechtliche-orientierung-angehoerige-puk-zuerich.pdf",
    pages: "PDF · 2 Seiten A4",
    mode: "download",
    quality: "core",
  }),
};

const handouts = {
  a1_bipolare_stoerung_verstehen: asset({
    key: "a1_bipolare_stoerung_verstehen",
    url: "/handouts/a1_bipolare_stoerung_verstehen.pdf",
    title: "Die bipolare Störung verstehen",
    subtitle: "Phasen, Muster und Verlauf einordnen",
    assetId: "HO-29",
    version: "web_v01",
    updated: "2026-05-17",
    filename: "a1_bipolare_stoerung_verstehen.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  a2_phasenverlauf: asset({
    key: "a2_phasenverlauf",
    url: "/handouts/a2_phasenverlauf.pdf",
    title: "Bipolarer Phasenverlauf",
    subtitle: "Manie, Hypomanie, Depression und stabile Phasen einordnen",
    assetId: "HO-30",
    version: "web_v01",
    updated: "2026-05-17",
    filename: "a2_phasenverlauf.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  a6_bipolar_i_ii_mischzustaende: asset({
    key: "a6_bipolar_i_ii_mischzustaende",
    url: "/handouts/a6_bipolar_i_ii_mischzustaende.pdf",
    title: "Bipolar I, II und Mischbilder verstehen",
    subtitle: "Hochphase, Depression und gemischte Merkmale unterscheiden",
    assetId: "HO-31",
    version: "web_v01",
    updated: "2026-05-17",
    filename: "a6_bipolar_i_ii_mischzustaende.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  a8_warnsignale: asset({
    key: "a8_warnsignale",
    url: "/handouts/a8_warnsignale.pdf",
    title: "Warnsignale früh erkennen",
    subtitle: "Ampel für Muster, Gespräche und nächste Schritte",
    assetId: "HO-01",
    version: "web_v03",
    updated: "2026-05-17",
    filename: "a8_warnsignale.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  absprachen_bevor_es_kippt: asset({
    key: "absprachen_bevor_es_kippt",
    url: "/handouts/absprachen_bevor_es_kippt.pdf",
    title: "Absprachen, bevor es kippt",
    subtitle: "Absprachekarte für Warnzeichen, Einbezug und Schutzwege",
    assetId: "HO-32",
    version: "web_v01",
    updated: "2026-05-17",
    filename: "absprachen_bevor_es_kippt.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  schwieriges_ruhig_ansprechen: asset({
    key: "schwieriges_ruhig_ansprechen",
    url: "/handouts/schwieriges_ruhig_ansprechen.pdf",
    title: "Schwieriges ruhig ansprechen",
    subtitle: "Drei-Satz-Karte für Beobachtung, Sorge und nächsten Schritt",
    assetId: "HO-33",
    version: "web_v01",
    updated: "2026-05-17",
    filename: "schwieriges_ruhig_ansprechen.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  behandlung_verstehen: asset({
    key: "behandlung_verstehen",
    url: "/handouts/behandlung_verstehen.pdf",
    title: "Behandlung gemeinsam verstehen",
    subtitle: "Behandlungskompass für Phase, Ziel und Rückfallvorbeugung",
    assetId: "HO-34",
    version: "web_v02",
    updated: "2026-05-17",
    filename: "behandlung_verstehen.pdf",
    pages: "A4 quer · 2 Seiten",
    mode: "preview",
    quality: "new",
  }),
  wenn_behandlung_abgelehnt_wird: asset({
    key: "wenn_behandlung_abgelehnt_wird",
    url: "/handouts/wenn_behandlung_abgelehnt_wird.pdf",
    title: "Wenn Behandlung abgelehnt wird",
    subtitle: "Drei-Spuren-Karte für Sorge, Vorsorge und akute Sicherheit",
    assetId: "HO-35",
    version: "web_v02",
    updated: "2026-05-17",
    filename: "wenn_behandlung_abgelehnt_wird.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  eltern_mit_bipolarer_stoerung: asset({
    key: "eltern_mit_bipolarer_stoerung",
    url: "/handouts/eltern_mit_bipolarer_stoerung.pdf",
    title: "Eltern bleiben – auch mit bipolarer Erkrankung",
    subtitle: "Schutzkreis, Kinder-Plan und altersgerechte Worte",
    assetId: "HO-36",
    version: "web_v02",
    updated: "2026-05-17",
    filename: "eltern_mit_bipolarer_stoerung.pdf",
    pages: "A4 hoch · 2 Seiten",
    mode: "preview",
    quality: "new",
  }),
  b1_18_belastungen: asset({
    key: "b1_18_belastungen",
    url: "/handouts/b1_18_belastungen.pdf",
    title: "18 Belastungen",
    subtitle: "Typische Belastungsmuster von Angehörigen",
    assetId: "HO-02",
    version: "web_v03",
    updated: "2026-05-12",
    filename: "b1_18_belastungen.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  a5_affiliate_stigma: asset({
    key: "a5_affiliate_stigma",
    url: "/handouts/a5_affiliate_stigma.pdf",
    title: "Stigma der Angehörigen",
    subtitle: "Wie Beschämung und Schweigen Angehörige treffen",
    assetId: "HO-03",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "a5_affiliate_stigma.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  b9_depression_partner: asset({
    key: "b9_depression_partner",
    url: "/handouts/b9_depression_partner.pdf",
    title: "Depression bei Angehörigen",
    subtitle: "Wenn die Belastung Sie selbst krank macht",
    assetId: "HO-04",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b9_depression_partner.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  b10_trennung_scheidung: asset({
    key: "b10_trennung_scheidung",
    url: "/handouts/b10_trennung_scheidung.pdf",
    title: "Beziehung an Grenzen",
    subtitle: "Entscheidungshilfe bei Trennung und Scheidung",
    assetId: "HO-05",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b10_trennung_scheidung.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  a4_ambiguous_loss: asset({
    key: "a4_ambiguous_loss",
    url: "/handouts/a4_ambiguous_loss.pdf",
    title: "Trauer ohne klaren Abschied",
    subtitle: "Wenn jemand da ist und vertraute Nähe fehlt",
    assetId: "HO-06",
    version: "web_v03",
    updated: "2026-05-17",
    filename: "a4_ambiguous_loss.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  b2_erosion_solidaritaet: asset({
    key: "b2_erosion_solidaritaet",
    url: "/handouts/b2_erosion_solidaritaet.pdf",
    title: "Beziehung unter Druck",
    subtitle: "Wie die Erkrankung Solidarität und Alltag erodiert",
    assetId: "HO-07",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b2_erosion_solidaritaet.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  b4_mechanismen_erosion: asset({
    key: "b4_mechanismen_erosion",
    url: "/handouts/b4_mechanismen_erosion.pdf",
    title: "Schonhaltung und Co-Isolation",
    subtitle: "Wie Belastung die Angehörigenperson verändert",
    assetId: "HO-08",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b4_mechanismen_erosion.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  // b3_kritische_zeitpunkte: in Welle 8 promotet — siehe downloads.kritischeZeitpunkte.
  // Physische /handouts/b3_kritische_zeitpunkte.pdf bleibt für Bookmark-Backward-Compat.
  b5_loyalitaetskonflikte: asset({
    key: "b5_loyalitaetskonflikte",
    url: "/handouts/b5_loyalitaetskonflikte.pdf",
    title: "Loyalitätskonflikte",
    subtitle: "Das Spannungsfeld verstehen",
    assetId: "HO-10",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b5_loyalitaetskonflikte.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  expressed_emotions: asset({
    key: "expressed_emotions",
    url: "/handouts/expressed_emotions.pdf",
    title: "Kritik, Überforderung, Teufelskreis",
    subtitle: "Wie Überlastung in Kritik, Rückzug und Kontrolle kippen kann",
    assetId: "HO-11",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "expressed_emotions.pdf",
    pages: "PDF-Handout · 2 Seiten A4",
    mode: "preview",
    quality: "regenerated",
  }),
  grenzsetzung: asset({
    key: "grenzsetzung",
    url: "/handouts/grenzsetzung.pdf",
    title: "Grenzsetzung",
    subtitle: "Praktische Strategien und Formulierungen",
    assetId: "HO-12",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "grenzsetzung.pdf",
    pages: "PDF-Handout · 2 Seiten A4",
    mode: "preview",
    quality: "regenerated",
  }),
  a3_ambivalente_loyalitaet: asset({
    key: "a3_ambivalente_loyalitaet",
    url: "/handouts/a3_ambivalente_loyalitaet.pdf",
    title: "Ambivalente Loyalität",
    subtitle: "Warum Liebe, Wut, Schuld und Erschöpfung gleichzeitig da sein können",
    assetId: "HO-13",
    version: "web_v03",
    updated: "2026-05-17",
    filename: "a3_ambivalente_loyalitaet.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  c1_krisenplan: asset({
    key: "c1_krisenplan",
    url: "/handouts/c1_krisenplan.pdf",
    title: "Krisenplan erstellen",
    subtitle: "Gemeinsame Orientierung für belastende Phasen",
    assetId: "HO-14",
    version: "web_v03",
    updated: "2026-05-13",
    filename: "c1_krisenplan.pdf",
    pages: "PDF-Handout · 2 Seiten A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c2_suizidgedanken: asset({
    key: "c2_suizidgedanken",
    url: "/handouts/c2_suizidgedanken.pdf",
    title: "Umgang mit Suizidgedanken",
    subtitle: "Ansprechen rettet Leben",
    assetId: "HO-15",
    version: "web_v03",
    updated: "2026-05-13",
    filename: "c2_suizidgedanken.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c3_psychose_wahn: asset({
    key: "c3_psychose_wahn",
    url: "/handouts/c3_psychose_wahn.pdf",
    title: "Psychose / Wahn",
    subtitle: "Was hilft, wenn Kontakt und Realität entgleiten",
    assetId: "HO-16",
    version: "web_v03",
    updated: "2026-05-13",
    filename: "c3_psychose_wahn.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c4_manie: asset({
    key: "c4_manie",
    url: "/handouts/c4_manie.pdf",
    title: "Umgang mit Manie",
    subtitle: "Praktische Strategien",
    assetId: "HO-17",
    version: "web_v03",
    updated: "2026-05-13",
    filename: "c4_manie.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c5_depression: asset({
    key: "c5_depression",
    url: "/handouts/c5_depression.pdf",
    title: "Umgang mit Depression",
    subtitle: "Wenn die erkrankte Person nicht erreichbar ist",
    assetId: "HO-18",
    version: "web_v03",
    updated: "2026-05-13",
    filename: "c5_depression.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  b7_behandlung_ambivalenz: asset({
    key: "b7_behandlung_ambivalenz",
    url: "/handouts/b7_behandlung_ambivalenz.pdf",
    title: "Behandlung und Ambivalenz",
    subtitle: "Warum Hilfe wichtig ist und gleichzeitig schwer werden kann",
    assetId: "HO-19",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "b7_behandlung_ambivalenz.pdf",
    pages: "PDF-Handout · 2 Seiten A4",
    mode: "preview",
    quality: "regenerated",
  }),
  // rechtliche_orientierung: in Welle 8 promotet — siehe downloads.rechtlicheOrientierung.
  // Physische /handouts/rechtliche_orientierung.pdf bleibt für Bookmark-Backward-Compat.
  c6_selbstfuersorge: asset({
    key: "c6_selbstfuersorge",
    url: "/handouts/c6_selbstfuersorge.pdf",
    title: "Die eigenen Kräfte schützen",
    subtitle: "Selbstfürsorge als Belastungsmanagement",
    assetId: "HO-22",
    version: "web_v03",
    updated: "2026-05-17",
    filename: "c6_selbstfuersorge.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  d4_solidaritaet_wellen: asset({
    key: "d4_solidaritaet_wellen",
    url: "/handouts/d4_solidaritaet_wellen.pdf",
    title: "Was langfristig trägt",
    subtitle: "Praxisstruktur für die lange Strecke",
    assetId: "HO-23",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "d4_solidaritaet_wellen.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  transformationsreise: asset({
    key: "transformationsreise",
    url: "/handouts/transformationsreise.pdf",
    title: "Veränderung über Zeit",
    subtitle: "Wachstum ohne Pflicht zur positiven Bilanz",
    assetId: "HO-24",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "transformationsreise.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  trialog: asset({
    key: "trialog",
    url: "/handouts/trialog.pdf",
    title: "Trialog und Zusammenarbeit",
    subtitle: "Drei Perspektiven sichtbar machen",
    assetId: "HO-25",
    version: "web_v02",
    updated: "2026-05-13",
    filename: "trialog.pdf",
    pages: "A4 · 2 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  b6_geschlechtsspezifisch: asset({
    key: "b6_geschlechtsspezifisch",
    url: "/handouts/b6_geschlechtsspezifisch.pdf",
    title: "Wenn Belastung unterschiedlich sichtbar wird",
    subtitle: "Rollenmuster, Sichtbarkeit und Erwartungsdruck einordnen",
    assetId: "HO-26",
    version: "web_v03",
    updated: "2026-05-12",
    filename: "b6_geschlechtsspezifisch.pdf",
    pages: "A4 · 3 Seiten",
    mode: "preview",
    quality: "regenerated",
  }),
  a9_schlaf_fruehwarnsystem: asset({
    key: "a9_schlaf_fruehwarnsystem",
    url: "/handouts/a9_schlaf_fruehwarnsystem.pdf",
    title: "Schlaf als Frühwarnsystem",
    subtitle: "Schlaf, Energie und Tempo als frühes Muster einordnen",
    assetId: "HO-27",
    version: "web_v02",
    updated: "2026-05-17",
    filename: "a9_schlaf_fruehwarnsystem.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
  b11_hypervigilanz_erschoepfung: asset({
    key: "b11_hypervigilanz_erschoepfung",
    url: "/handouts/b11_hypervigilanz_erschoepfung.pdf",
    title: "Ständige Wachsamkeit und Erschöpfung",
    subtitle: "Wie Dauer-Wachsamkeit nach Krisen Kraft bindet",
    assetId: "HO-28",
    version: "web_v02",
    updated: "2026-05-17",
    filename: "b11_hypervigilanz_erschoepfung.pdf",
    pages: "A4 quer · 1 Seite",
    mode: "preview",
    quality: "new",
  }),
};

const groups = {
  canonicalHandouts: [
    handouts.a1_bipolare_stoerung_verstehen,
    handouts.a2_phasenverlauf,
    handouts.a6_bipolar_i_ii_mischzustaende,
    handouts.behandlung_verstehen,
    handouts.a9_schlaf_fruehwarnsystem,
    handouts.a8_warnsignale,
    handouts.b11_hypervigilanz_erschoepfung,
    handouts.c6_selbstfuersorge,
    handouts.a3_ambivalente_loyalitaet,
    handouts.a4_ambiguous_loss,
    handouts.eltern_mit_bipolarer_stoerung,
    handouts.absprachen_bevor_es_kippt,
    handouts.schwieriges_ruhig_ansprechen,
    handouts.wenn_behandlung_abgelehnt_wird,
  ],
  modul1: [handouts.a1_bipolare_stoerung_verstehen, handouts.a2_phasenverlauf, handouts.a6_bipolar_i_ii_mischzustaende, handouts.behandlung_verstehen, handouts.a9_schlaf_fruehwarnsystem, handouts.a8_warnsignale],
  modul2: [handouts.b11_hypervigilanz_erschoepfung, handouts.c6_selbstfuersorge],
  modul3: [handouts.a3_ambivalente_loyalitaet, handouts.a4_ambiguous_loss],
  modul4: [handouts.b11_hypervigilanz_erschoepfung, handouts.a4_ambiguous_loss, handouts.c6_selbstfuersorge],
  modul5: [handouts.a3_ambivalente_loyalitaet, handouts.a4_ambiguous_loss, handouts.eltern_mit_bipolarer_stoerung],
  modul6: [handouts.absprachen_bevor_es_kippt, handouts.schwieriges_ruhig_ansprechen, handouts.wenn_behandlung_abgelehnt_wird, handouts.a8_warnsignale],
  modul7: [handouts.c6_selbstfuersorge, handouts.b11_hypervigilanz_erschoepfung],
  modul8TopDownloads: [downloads.notfallkarte, downloads.krisenplanVorlage, downloads.kurzblattStabilisiert],
  modul8TopArchive: [handouts.c6_selbstfuersorge, handouts.a4_ambiguous_loss],
  modul8ArchiveEntries: [
    { badge: "M1", asset: handouts.a1_bipolare_stoerung_verstehen },
    { badge: "M1", asset: handouts.a2_phasenverlauf },
    { badge: "M1", asset: handouts.a6_bipolar_i_ii_mischzustaende },
    { badge: "M1", asset: handouts.behandlung_verstehen },
    { badge: "M1", asset: handouts.a9_schlaf_fruehwarnsystem },
    { badge: "M1", asset: handouts.a8_warnsignale },
    { badge: "M2", asset: handouts.b11_hypervigilanz_erschoepfung },
    { badge: "M7", asset: handouts.c6_selbstfuersorge },
    { badge: "M5", asset: handouts.a3_ambivalente_loyalitaet },
    { badge: "M4", asset: handouts.a4_ambiguous_loss },
    { badge: "M5", asset: handouts.eltern_mit_bipolarer_stoerung },
    { badge: "M6", asset: handouts.absprachen_bevor_es_kippt },
    { badge: "M6", asset: handouts.schwieriges_ruhig_ansprechen },
    { badge: "M6", asset: handouts.wenn_behandlung_abgelehnt_wird },
  ],
  notfall: [downloads.suizidgedanken, downloads.manie, downloads.depression, downloads.psychoseWahn],
  publicDownloads: [
    downloads.notfallkarte,
    downloads.krisenplanVorlage,
    downloads.kurzblattStabilisiert,
    downloads.suizidgedanken,
    downloads.manie,
    downloads.depression,
    downloads.psychoseWahn,
    downloads.kritischeZeitpunkte,
    downloads.rechtlicheOrientierung,
  ],
};

const legacyPdfAliases = [];

module.exports = {
  downloads,
  handouts,
  groups,
  legacyPdfAliases,
};
