const asset = ({
  key,
  url,
  title,
  subtitle,
  assetId,
  version,
  updated,
  filename,
  pages,
  mode,
  quality,
  kind = "pdf",
}) => ({
  key,
  url,
  title,
  subtitle,
  assetId,
  version,
  updated,
  filename,
  pages,
  mode,
  quality,
  kind,
  metaLine: [assetId, version, updated].filter(Boolean).join(" · "),
});

const downloads = {
  notfallkarte: asset({
    key: "notfallkarte",
    url: "/downloads/notfallkarte-kanton-zuerich-puk.pdf",
    title: "Notfallkarte Kanton Zürich",
    subtitle: "Alle wichtigen Nummern mit kurzer Einordnung",
    assetId: "DL-01",
    version: "core_v01",
    updated: "2026-04-20",
    filename: "notfallkarte-kanton-zuerich-puk.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
  krisenplanVorlage: asset({
    key: "krisenplanVorlage",
    url: "/downloads/krisenplan-vorlage-bipolare-stoerung-puk-zuerich.pdf",
    title: "Krisenplan-Vorlage",
    subtitle: "Vorlage zum Ausfüllen für stabile Phasen",
    assetId: "DL-02",
    version: "core_v01",
    updated: "2026-04-20",
    filename: "krisenplan-vorlage-bipolare-stoerung-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4 · ausfüllbar",
    mode: "download",
    quality: "core",
  }),
  kurzblattStabilisiert: asset({
    key: "kurzblattStabilisiert",
    url: "/downloads/kurzblatt-was-stabilisiert-was-schadet-puk-zuerich.pdf",
    title: "Was stabilisiert — was schadet",
    subtitle: "Kompaktes Blatt für Kommunikation, Selbstfürsorge und Grenzen",
    assetId: "DL-03",
    version: "core_v01",
    updated: "2026-04-20",
    filename: "kurzblatt-was-stabilisiert-was-schadet-puk-zuerich.pdf",
    pages: "PDF · 1 Seite A4",
    mode: "download",
    quality: "core",
  }),
};

const handouts = {
  a8_warnsignale: asset({
    key: "a8_warnsignale",
    url: "/handouts/a8_warnsignale.pdf",
    title: "Warnsignale — Ampelsystem",
    subtitle: "Frühwarnzeichen erkennen",
    assetId: "HO-01",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "a8_warnsignale.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  b1_18_belastungen: asset({
    key: "b1_18_belastungen",
    url: "/handouts/b1_18_belastungen.pdf",
    title: "18 Belastungen",
    subtitle: "Typische Belastungsmuster von Angehörigen",
    assetId: "HO-02",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b1_18_belastungen.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  a5_affiliate_stigma: asset({
    key: "a5_affiliate_stigma",
    url: "/handouts/a5_affiliate_stigma.pdf",
    title: "Stigma der Angehörigen",
    subtitle: "Wie Beschämung und Schweigen Angehörige treffen",
    assetId: "HO-03",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "a5_affiliate_stigma.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  b9_depression_partner: asset({
    key: "b9_depression_partner",
    url: "/handouts/b9_depression_partner.pdf",
    title: "Depression bei Angehörigen",
    subtitle: "Wenn die Belastung Sie selbst krank macht",
    assetId: "HO-04",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b9_depression_partner.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  b10_trennung_scheidung: asset({
    key: "b10_trennung_scheidung",
    url: "/handouts/b10_trennung_scheidung.pdf",
    title: "Beziehung an Grenzen",
    subtitle: "Entscheidungshilfe bei Trennung und Scheidung",
    assetId: "HO-05",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b10_trennung_scheidung.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  a4_ambiguous_loss: asset({
    key: "a4_ambiguous_loss",
    url: "/handouts/a4_ambiguous_loss.pdf",
    title: "Trauer ohne klaren Abschied",
    subtitle: "Trauer um jemanden, der noch da ist",
    assetId: "HO-06",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "a4_ambiguous_loss.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  b2_erosion_solidaritaet: asset({
    key: "b2_erosion_solidaritaet",
    url: "/handouts/b2_erosion_solidaritaet.pdf",
    title: "Beziehung unter Druck",
    subtitle: "Wie die Erkrankung Solidarität und Alltag erodiert",
    assetId: "HO-07",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "b2_erosion_solidaritaet.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  b4_mechanismen_erosion: asset({
    key: "b4_mechanismen_erosion",
    url: "/handouts/b4_mechanismen_erosion.pdf",
    title: "Schonhaltung und Co-Isolation",
    subtitle: "Wie Belastung die Angehörigenperson verändert",
    assetId: "HO-08",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "b4_mechanismen_erosion.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  b3_kritische_zeitpunkte: asset({
    key: "b3_kritische_zeitpunkte",
    url: "/handouts/b3_kritische_zeitpunkte.pdf",
    title: "Kritische Zeitpunkte",
    subtitle: "Wann wird es besonders schwer?",
    assetId: "HO-09",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b3_kritische_zeitpunkte.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  b5_loyalitaetskonflikte: asset({
    key: "b5_loyalitaetskonflikte",
    url: "/handouts/b5_loyalitaetskonflikte.pdf",
    title: "Loyalitätskonflikte",
    subtitle: "Das Spannungsfeld verstehen",
    assetId: "HO-10",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b5_loyalitaetskonflikte.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  expressed_emotions: asset({
    key: "expressed_emotions",
    url: "/handouts/expressed_emotions.pdf",
    title: "Kritik, Überforderung, Teufelskreis",
    subtitle: "Wie Überlastung in Kritik, Rückzug und Kontrolle kippen kann",
    assetId: "HO-06",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "expressed_emotions.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  grenzsetzung: asset({
    key: "grenzsetzung",
    url: "/handouts/grenzsetzung.pdf",
    title: "Grenzsetzung",
    subtitle: "Praktische Strategien und Formulierungen",
    assetId: "HO-12",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "grenzsetzung.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  a3_ambivalente_loyalitaet: asset({
    key: "a3_ambivalente_loyalitaet",
    url: "/handouts/a3_ambivalente_loyalitaet.pdf",
    title: "Ambivalente Loyalität",
    subtitle: "Warum Nähe, Pflicht und Erschöpfung gleichzeitig auftreten",
    assetId: "HO-13",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "a3_ambivalente_loyalitaet.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  c1_krisenplan: asset({
    key: "c1_krisenplan",
    url: "/handouts/c1_krisenplan.pdf",
    title: "Krisenplan erstellen",
    subtitle: "Gemeinsame Orientierung für belastende Phasen",
    assetId: "HO-14",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c1_krisenplan.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c2_suizidgedanken: asset({
    key: "c2_suizidgedanken",
    url: "/handouts/c2_suizidgedanken.pdf",
    title: "Umgang mit Suizidgedanken",
    subtitle: "Ansprechen rettet Leben",
    assetId: "HO-15",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c2_suizidgedanken.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c3_psychose_wahn: asset({
    key: "c3_psychose_wahn",
    url: "/handouts/c3_psychose_wahn.pdf",
    title: "Psychose / Wahn",
    subtitle: "Was hilft, wenn Kontakt und Realität entgleiten",
    assetId: "HO-16",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c3_psychose_wahn.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c4_manie: asset({
    key: "c4_manie",
    url: "/handouts/c4_manie.pdf",
    title: "Umgang mit Manie",
    subtitle: "Praktische Strategien",
    assetId: "HO-17",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c4_manie.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c5_depression: asset({
    key: "c5_depression",
    url: "/handouts/c5_depression.pdf",
    title: "Umgang mit Depression",
    subtitle: "Wenn die erkrankte Person nicht erreichbar ist",
    assetId: "HO-18",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c5_depression.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  b7_behandlung_ambivalenz: asset({
    key: "b7_behandlung_ambivalenz",
    url: "/handouts/b7_behandlung_ambivalenz.pdf",
    title: "Behandlung und Ambivalenz",
    subtitle: "Warum Hilfe wichtig ist und gleichzeitig schwer werden kann",
    assetId: "HO-19",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "b7_behandlung_ambivalenz.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  rechtliche_orientierung: asset({
    key: "rechtliche_orientierung",
    url: "/handouts/rechtliche_orientierung.pdf",
    title: "Rechtliche Orientierung",
    subtitle: "FU, KESB und Vorsorgeauftrag im Überblick",
    assetId: "HO-20",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "rechtliche_orientierung.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
  brief_an_betroffene: asset({
    key: "brief_an_betroffene",
    url: "/handouts/brief-an-betroffene.pdf",
    title: "Brief an Betroffene",
    subtitle: "Was Angehörige durchmachen — zum Weitergeben",
    assetId: "HO-21",
    version: "web_v01",
    updated: "2026-04-20",
    filename: "brief-an-betroffene.pdf",
    pages: "PDF-Handout · 1 Seite A4",
    mode: "preview",
    quality: "regenerated",
  }),
  c6_selbstfuersorge: asset({
    key: "c6_selbstfuersorge",
    url: "/handouts/c6_selbstfuersorge.pdf",
    title: "Selbstfürsorge als Belastungsmanagement",
    subtitle: "Schutz vor Auszehrung im Alltag",
    assetId: "HO-22",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "c6_selbstfuersorge.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  d4_solidaritaet_wellen: asset({
    key: "d4_solidaritaet_wellen",
    url: "/handouts/d4_solidaritaet_wellen.pdf",
    title: "Was langfristig trägt",
    subtitle: "Fünf Säulen für die lange Strecke",
    assetId: "HO-23",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "d4_solidaritaet_wellen.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  transformationsreise: asset({
    key: "transformationsreise",
    url: "/handouts/transformationsreise.pdf",
    title: "Veränderung über Zeit",
    subtitle: "Wachstum ohne Pflicht zur positiven Bilanz",
    assetId: "HO-24",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "transformationsreise.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  trialog: asset({
    key: "trialog",
    url: "/handouts/trialog.pdf",
    title: "Trialog und Zusammenarbeit",
    subtitle: "Drei Perspektiven sichtbar machen",
    assetId: "HO-25",
    version: "web_v02",
    updated: "2026-04-20",
    filename: "trialog.pdf",
    pages: "A4 · 1 Seite",
    mode: "preview",
    quality: "regenerated",
  }),
  b6_geschlechtsspezifisch: asset({
    key: "b6_geschlechtsspezifisch",
    url: "/handouts/b6_geschlechtsspezifisch.pdf",
    title: "Geschlechtsspezifische Nuancen",
    subtitle: "Wie Rollenbilder Belastungen mitprägen",
    assetId: "HO-26",
    version: "archiv_v01",
    updated: "Stand offen",
    filename: "b6_geschlechtsspezifisch.pdf",
    pages: "Archiv-Handout · ältere Fassung",
    mode: "preview",
    quality: "archive",
  }),
};

const groups = {
  modul1: [handouts.a8_warnsignale, handouts.c4_manie, handouts.c5_depression, handouts.b7_behandlung_ambivalenz],
  modul2: [handouts.b1_18_belastungen, handouts.a5_affiliate_stigma, handouts.b9_depression_partner],
  modul3: [handouts.b10_trennung_scheidung, handouts.b3_kritische_zeitpunkte],
  modul4: [handouts.a4_ambiguous_loss, handouts.b2_erosion_solidaritaet, handouts.b4_mechanismen_erosion],
  modul5: [handouts.b5_loyalitaetskonflikte, handouts.expressed_emotions, handouts.grenzsetzung, handouts.b10_trennung_scheidung],
  modul6: [handouts.c1_krisenplan, handouts.grenzsetzung, handouts.c4_manie, handouts.c5_depression, handouts.c2_suizidgedanken, handouts.rechtliche_orientierung, handouts.brief_an_betroffene],
  modul7: [handouts.c6_selbstfuersorge, handouts.d4_solidaritaet_wellen, handouts.trialog, handouts.transformationsreise],
  modul8TopDownloads: [downloads.notfallkarte, downloads.krisenplanVorlage, downloads.kurzblattStabilisiert],
  modul8TopArchive: [handouts.grenzsetzung, handouts.a4_ambiguous_loss],
  modul8ArchiveEntries: [
    { badge: "M1", asset: handouts.a8_warnsignale },
    { badge: "M2", asset: handouts.b1_18_belastungen },
    { badge: "M6", asset: handouts.c4_manie },
    { badge: "M6", asset: handouts.c5_depression },
    { badge: "M3", asset: handouts.b10_trennung_scheidung },
    { badge: "M4", asset: handouts.a4_ambiguous_loss },
    { badge: "M4", asset: handouts.b2_erosion_solidaritaet },
    { badge: "M4", asset: handouts.b4_mechanismen_erosion },
    { badge: "M4", asset: handouts.b3_kritische_zeitpunkte },
    { badge: "M5", asset: handouts.expressed_emotions },
    { badge: "M5", asset: handouts.b5_loyalitaetskonflikte },
    { badge: "M5", asset: handouts.a3_ambivalente_loyalitaet },
    { badge: "M5", asset: handouts.a5_affiliate_stigma },
    { badge: "M6", asset: handouts.c1_krisenplan },
    { badge: "M6", asset: handouts.grenzsetzung },
    { badge: "M6", asset: handouts.c2_suizidgedanken },
    { badge: "M6", asset: handouts.c3_psychose_wahn },
    { badge: "M6", asset: handouts.b7_behandlung_ambivalenz },
    { badge: "M7", asset: handouts.c6_selbstfuersorge },
    { badge: "M7", asset: handouts.d4_solidaritaet_wellen },
    { badge: "M7", asset: handouts.transformationsreise },
    { badge: "M7", asset: handouts.trialog },
    { badge: "M7", asset: handouts.b6_geschlechtsspezifisch },
    { badge: "M7", asset: handouts.b9_depression_partner },
  ],
  notfall: [handouts.c2_suizidgedanken, handouts.c4_manie, handouts.c5_depression, handouts.c3_psychose_wahn],
};

module.exports = {
  downloads,
  handouts,
  groups,
};
