const sourceEntries = [
  {
    id: "nice-cg185",
    type: "Leitlinie",
    short: "NICE CG185",
    title: "Bipolar disorder: assessment and management (CG185)",
    authors: "National Institute for Health and Care Excellence",
    year: "2014, zuletzt aktualisiert 2023",
    publisher: "NICE, Vereinigtes Königreich",
    url: "https://www.nice.org.uk/guidance/cg185",
    note: "Zentrale englischsprachige Versorgungsleitlinie mit Empfehlungen zu Diagnostik, Pharmakotherapie, Psychotherapie und Krisenintervention.",
  },
  {
    id: "canmat-2018",
    type: "Leitlinie",
    short: "CANMAT/ISBD 2018",
    title: "Canadian Network for Mood and Anxiety Treatments (CANMAT) and International Society for Bipolar Disorders (ISBD) 2018 guidelines for the management of patients with bipolar disorder",
    authors: "Yatham LN, Kennedy SH, Parikh SV, Schaffer A, Bond DJ, Frey BN, et al.",
    year: "2018",
    publisher: "Bipolar Disorders 20(2):97-170",
    url: "https://onlinelibrary.wiley.com/doi/10.1111/bdi.12609",
    note: "International stark rezipierte, evidenzbasierte Empfehlungen, auf die auch im schweizerischen Versorgungskontext häufig Bezug genommen wird.",
  },
  {
    id: "canmat-family-guide",
    type: "Leitlinie",
    short: "CANMAT Patienten- und Angehörigenleitfaden",
    title: "Patient and Family Guide to the CANMAT and ISBD Guidelines on the Management of Bipolar Disorder",
    authors: "CANMAT/ISBD",
    year: "2020",
    publisher: "CANMAT",
    url: "https://www.canmat.org/wp-content/uploads/2020/03/Patient-and-Family-Guide-to-the-CANMAT-and-ISBD-Guidelines-on-Bipolar-Disorder-FINAL.pdf",
    note: "Laienverständliche Übersetzung der CANMAT/ISBD-Leitlinie für Betroffene und Angehörige.",
  },
  {
    id: "s3-dgbs-2019",
    type: "Leitlinie",
    short: "S3-Leitlinie DGBS/DGPPN",
    title: "S3-Leitlinie zur Diagnostik und Therapie bipolarer Störungen",
    authors: "DGBS e.V. und DGPPN e.V. (Hrsg.)",
    year: "2019, Langfassung Version 2.0; Aktualisierung in Bearbeitung 2024",
    publisher: "Deutsche Gesellschaft für Bipolare Störungen / Deutsche Gesellschaft für Psychiatrie und Psychotherapie",
    url: "https://www.leitlinien.de/themen/bipolare-stoerungen",
    note: "Wichtigste deutschsprachige Leitlinie und für den DACH-Raum besonders relevant.",
  },
  {
    id: "wfsbp-2018",
    type: "Leitlinie",
    short: "WFSBP 2018",
    title: "World Federation of Societies of Biological Psychiatry (WFSBP) Guidelines for the Biological Treatment of Bipolar Disorders",
    authors: "Grunze H, Vieta E, Goodwin GM, et al.",
    year: "2018 (Update Akut-Manie und Erhaltungstherapie)",
    publisher: "The World Journal of Biological Psychiatry",
    url: "https://www.tandfonline.com/journals/iwbp20",
    note: "Internationaler Standard der biologisch-psychiatrischen Behandlung, ergaenzend zu CANMAT und NICE.",
  },
  {
    id: "icd-11",
    type: "Klassifikation",
    short: "ICD-11",
    title: "International Classification of Diseases, 11. Revision - Kapitel 06: Mental, behavioural or neurodevelopmental disorders",
    authors: "World Health Organization",
    year: "in Kraft seit 2022",
    publisher: "WHO",
    url: "https://icd.who.int/browse11/l-m/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f1813598989",
    note: "Diagnostische Klassifikation, in der Bipolar-I, Bipolar-II und Zyklothymie kodiert sind.",
  },
  {
    id: "dsm-5-tr",
    type: "Klassifikation",
    short: "DSM-5-TR",
    title: "Diagnostic and Statistical Manual of Mental Disorders, Fifth Edition, Text Revision",
    authors: "American Psychiatric Association",
    year: "2022",
    publisher: "APA Publishing",
    url: "https://www.psychiatry.org/psychiatrists/practice/dsm",
    note: "In Forschung und Lehre häufig parallel zur ICD-11 genutzt.",
  },
  {
    id: "miklowitz-2008",
    type: "Uebersichtsarbeit",
    short: "Miklowitz 2008",
    title: "Adjunctive psychotherapy for bipolar disorder: state of the evidence",
    authors: "Miklowitz DJ",
    year: "2008",
    publisher: "American Journal of Psychiatry 165(11):1408-1419",
    url: "https://ajp.psychiatryonline.org/doi/10.1176/appi.ajp.2008.08040488",
    note: "Belegt, dass familienfokussierte Therapie und Psychoedukation Rückfallraten zusätzlich zur Medikation senken können.",
  },
  {
    id: "miklowitz-2014",
    type: "Studie",
    short: "Miklowitz 2014",
    title: "Family-focused treatment for adolescents and young adults at high risk for psychosis: results of a randomized trial",
    authors: "Miklowitz DJ, O'Brien MP, Schlosser DA, et al.",
    year: "2014",
    publisher: "Journal of the American Academy of Child & Adolescent Psychiatry 53(8):848-858",
    url: "https://www.jaacap.org/article/S0890-8567(14)00347-1/fulltext",
    note: "Unterstützt die Wirksamkeit familienfokussierter Therapie auch in jüngeren Altersgruppen.",
  },
  {
    id: "colom-2003",
    type: "Studie",
    short: "Colom 2003",
    title: "A randomized trial on the efficacy of group psychoeducation in the prophylaxis of recurrences in bipolar patients whose disease is in remission",
    authors: "Colom F, Vieta E, Martinez-Aran A, et al.",
    year: "2003",
    publisher: "Archives of General Psychiatry 60(4):402-407",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/207601",
    note: "Klassische Studie zur Wirksamkeit strukturierter Psychoedukation auf Rückfallraten.",
  },
  {
    id: "reinares-2008",
    type: "Studie",
    short: "Reinares 2008",
    title: "Impact of caregiver group psychoeducation on the course and outcome of bipolar patients in remission",
    authors: "Reinares M, Colom F, Sanchez-Moreno J, et al.",
    year: "2008",
    publisher: "Bipolar Disorders 10(4):511-519",
    url: "https://onlinelibrary.wiley.com/doi/10.1111/j.1399-5618.2008.00588.x",
    note: "Zeigt, dass Psychoedukation für Angehörige Stabilitätsphasen der Erkrankten verlängern kann.",
  },
  {
    id: "sotomo-sby-2024",
    type: "Studie",
    short: "Sotomo / Stand by You 2024",
    title: "Stand By You - Psychische Belastung von Angehörigen psychisch erkrankter Menschen in der Schweiz",
    authors: "Forschungsstelle Sotomo, im Auftrag der Stand By You-Initiative",
    year: "2024",
    publisher: "sotomo.ch",
    url: "https://sotomo.ch/site/wp-content/uploads/2024/03/sby_studie_final.pdf",
    note: "Repräsentative Schweizer Befragung zu Belastung, Isolation und fehlender gesellschaftlicher Resonanz bei Angehörigen.",
  },
  {
    id: "miklowitz-ee-2007",
    type: "Uebersichtsarbeit",
    short: "Miklowitz 2007 (EE)",
    title: "The role of the family in the course and treatment of bipolar disorder",
    authors: "Miklowitz DJ",
    year: "2007",
    publisher: "Current Directions in Psychological Science 16(4):192-196",
    url: "https://journals.sagepub.com/doi/10.1111/j.1467-8721.2007.00502.x",
    note: "Ordnet das Konzept Expressed Emotion und dessen Bedeutung für den Krankheitsverlauf ein.",
  },
  {
    id: "dazzi-2014",
    type: "Uebersichtsarbeit",
    short: "Dazzi 2014",
    title: "Does asking about suicide and related behaviours induce suicidal ideation? What is the evidence?",
    authors: "Dazzi T, Gribble R, Wessely S, Fear NT",
    year: "2014",
    publisher: "Psychological Medicine 44(16):3361-3363",
    url: "https://www.cambridge.org/core/journals/psychological-medicine/article/does-asking-about-suicide-and-related-behaviours-induce-suicidal-ideation-what-is-the-evidence/C76DD23F00B1AAB73AB6DE2EBD63E2BE",
    note: "Direktes Ansprechen von Suizidgedanken erhöht das Risiko nicht, sondern kann entlasten.",
  },
  {
    id: "plans-2019",
    type: "Uebersichtsarbeit",
    short: "Plans 2019",
    title: "Association between completed suicide and bipolar disorder: a systematic review of the literature",
    authors: "Plans L, Barrot C, Nieto E, et al.",
    year: "2019",
    publisher: "Journal of Affective Disorders 242:111-122",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S0165032718316811",
    note: "Belegt das erhöhte Suizidrisiko bei bipolarer Störung, besonders in Mischzuständen und depressiven Episoden mit manischen Anteilen.",
  },
  {
    id: "cipriani-li-2013",
    type: "Meta-Analyse",
    short: "Cipriani 2013",
    title: "Lithium in the prevention of suicide in mood disorders: updated systematic review and meta-analysis",
    authors: "Cipriani A, Hawton K, Stockton S, Geddes JR",
    year: "2013",
    publisher: "BMJ 346:f3646",
    url: "https://www.bmj.com/content/346/bmj.f3646",
    note: "Lithium kann die Suizidrate bei Bipolar-I und Bipolar-II in der Erhaltungstherapie senken.",
  },
  {
    id: "who-bipolar-factsheet",
    type: "Uebersichtsarbeit",
    short: "WHO Bipolar Fact Sheet",
    title: "Bipolar disorder - Fact sheet",
    authors: "World Health Organization",
    year: "Letzte Prüfung: 04/2026",
    publisher: "who.int",
    url: "https://www.who.int/news-room/fact-sheets/detail/bipolar-disorder",
    note: "Faktenseite der WHO zu Ursachen, Verlauf und globaler Einordnung bipolarer Störungen.",
  },
  {
    id: "lancet-bipolar-2025",
    type: "Uebersichtsarbeit",
    short: "Lancet Bipolar 2025",
    title: "Bipolar disorder (Seminar)",
    authors: "McIntyre RS et al.",
    year: "2025",
    publisher: "The Lancet",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S0140673625011407",
    note: "Aktuelle Übersicht zu bipolaren Störungen als multifaktorielles Geschehen mit biologischen, psychologischen und sozialen Einflussfaktoren.",
  },
  {
    id: "gwas-bipolar-2025",
    type: "Studie",
    short: "GWAS Bipolar 2025",
    title: "Genomics yields biological and phenotypic insights into bipolar disorder (PGC Bipolar)",
    authors: "Mullins N, O'Connell KS, Coleman JRI, et al. (Psychiatric Genomics Consortium)",
    year: "2025",
    publisher: "Nature / Maastricht University (PGC)",
    url: "https://cris.maastrichtuniversity.nl/en/publications/genomics-yields-biological-and-phenotypic-insights-into-bipolar-d/",
    note: "Grosse genomische Arbeit mit Hinweisen auf ein polygenes Modell ohne einzelnes Bipolar-Gen.",
  },
  {
    id: "molpsy-neurodev-2024",
    type: "Uebersichtsarbeit",
    short: "Molecular Psychiatry Neurodevelopment 2024",
    title: "Towards a neurodevelopmental model of bipolar disorder: a critical review of trait- and state-related functional neuroimaging in adolescents and young adults",
    authors: "Frangou S et al.",
    year: "2024",
    publisher: "Molecular Psychiatry",
    url: "https://www.nature.com/articles/s41380-024-02758-4",
    note: "Diskutiert ein vorläufiges neuroentwicklungsbezogenes Modell bipolarer Störungen.",
  },
  {
    id: "sleep-circadian-bipolar-2024",
    type: "Uebersichtsarbeit",
    short: "Schlaf und Rhythmus 2024",
    title: "Sleep and circadian disruption in bipolar disorders",
    authors: "Gold AK, Sylvia LG et al.",
    year: "2024",
    publisher: "Sleep Medicine Reviews / PubMed",
    url: "https://pubmed.ncbi.nlm.nih.gov/39210713/",
    note: "Schlaf- und zirkadiane Störungen sind über alle Krankheitsphasen relevant und mit Rückfällen, Lebensqualität und Suizidalität verknüpft.",
  },
  {
    id: "reward-social-rhythms-2024",
    type: "Studie",
    short: "Reward und soziale Rhythmen 2024",
    title: "Reward Sensitivity and Social Rhythms During Goal-Striving in Bipolar Spectrum Disorders",
    authors: "Alloy LB, Nusslock R et al.",
    year: "2024",
    publisher: "Journal of Affective Disorders / PMC",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10842638/",
    note: "Untersucht, wie Belohnungssensitivität und Zielverfolgung soziale Rhythmen verändern und (hypo)manische Aktivierung mitprägen können.",
  },
  {
    id: "lancet-psy-trauma-2016",
    type: "Uebersichtsarbeit",
    short: "Lancet Psychiatry Trauma 2016",
    title: "Childhood maltreatment and unfavourable clinical outcomes in bipolar disorder: a systematic review and meta-analysis",
    authors: "Agnew-Blais J, Danese A",
    year: "2016",
    publisher: "The Lancet Psychiatry",
    url: "https://www.sciencedirect.com/science/article/abs/pii/S2215036615005441",
    note: "Kindheitsbelastungen sind mit ungünstigerem Verlauf assoziiert, ohne einen monokausalen Verursachungsnachweis zu liefern.",
  },
  {
    id: "trauma-bipolar-2025",
    type: "Studie",
    short: "Childhood Trauma 2025",
    title: "The effect of childhood trauma on bipolar depression",
    authors: "Forschungsteam, peer-reviewed",
    year: "2025",
    publisher: "Scientific Reports / Nature",
    url: "https://www.nature.com/articles/s41598-025-98537-4",
    note: "Prospektive Daten zu früherem Beginn und schwererem Verlauf bipolarer Depression bei Kindheitstrauma.",
  },
  {
    id: "chronometabolic-2025",
    type: "Uebersichtsarbeit",
    short: "Chronometabolisch 2025",
    title: "Metabolic plasticity: an evolutionary perspective on metabolic and circadian dysregulation in bipolar disorder",
    authors: "Kato T et al.",
    year: "2025",
    publisher: "Molecular Psychiatry",
    url: "https://www.nature.com/articles/s41380-025-03123-9",
    note: "Beschreibt ein chronometabolisches Modell bipolarer Störungen mit gekoppelten zirkadianen und metabolischen Systemen.",
  },
  {
    id: "immuno-bipolar-2025",
    type: "Uebersichtsarbeit",
    short: "Immunsystem 2025",
    title: "Immune dysregulation and neuroinflammation in bipolar disorder: pathophysiological insights and therapeutic perspectives",
    authors: "Forschungsteam, Open Access",
    year: "2025",
    publisher: "Brain, Behavior & Immunity / ScienceDirect",
    url: "https://www.sciencedirect.com/science/article/pii/S2666354625002133",
    note: "Fasst Hinweise zu Entzündung, oxidativem Stress und Mikroglia-Aktivierung als mögliche Mitspieler zusammen.",
  },
  {
    id: "dynamical-bipolar-2022",
    type: "Uebersichtsarbeit",
    short: "Dynamische Modelle 2022",
    title: "A critical evaluation of dynamical systems models of bipolar disorder",
    authors: "Nestsiarovich A et al.",
    year: "2022",
    publisher: "Translational Psychiatry",
    url: "https://www.nature.com/articles/s41398-022-02194-4",
    note: "Ordnet bipolare Verläufe als dynamische Systeme mit Kipp-Punkten ein; vielversprechend, aber noch zu validieren.",
  },
  {
    id: "mcguffin-2003",
    type: "Studie",
    short: "McGuffin 2003",
    title: "The heritability of bipolar affective disorder and the genetic relationship to unipolar depression",
    authors: "McGuffin P, Rijsdijk F, Andrew M, Sham P, Katz R, Cardno A",
    year: "2003",
    publisher: "Archives of General Psychiatry 60(5):497-502",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/207725",
    note: "Schätzt die Heritabilität bipolarer Störungen im Rahmen eines Mehrfaktorenmodells auf 60-85 Prozent.",
  },
  {
    id: "judd-2002",
    type: "Studie",
    short: "Judd 2002",
    title: "The long-term natural history of the weekly symptomatic status of bipolar I disorder",
    authors: "Judd LL, Akiskal HS, Schettler PJ, et al.",
    year: "2002",
    publisher: "Archives of General Psychiatry 59(6):530-537",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/206820",
    note: "Langzeitstudie über mehr als 12 Jahre zum Anteil symptomfreier, depressiver, manischer und gemischter Phasen.",
  },
  {
    id: "merikangas-2011",
    type: "Studie",
    short: "Merikangas 2011",
    title: "Prevalence and correlates of bipolar spectrum disorder in the World Mental Health Survey initiative",
    authors: "Merikangas KR, Jin R, He JP, et al.",
    year: "2011",
    publisher: "Archives of General Psychiatry 68(3):241-251",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/1107207",
    note: "Grössere epidemiologische Einordnung des Bipolar-Spektrums und seiner Prävalenz.",
  },
  {
    id: "frank-2005",
    type: "Studie",
    short: "Frank 2005",
    title: "Two-year outcomes for interpersonal and social rhythm therapy in individuals with bipolar I disorder",
    authors: "Frank E, Kupfer DJ, Thase ME, et al.",
    year: "2005",
    publisher: "Archives of General Psychiatry 62(9):996-1004",
    url: "https://jamanetwork.com/journals/jamapsychiatry/fullarticle/208975",
    note: "Belegt die Wirksamkeit interpersoneller und sozialer Rhythmus-Therapie als Stabilisierungsansatz.",
  },
  {
    id: "puk-zh",
    type: "Schweizer Versorgung",
    short: "PUK Zürich Notfall Erwachsene",
    title: "Psychiatrische Universitätsklinik Zürich - Notfall Erwachsene",
    authors: "PUK Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "pukzh.ch",
    url: "https://www.pukzh.ch/notfall/erwachsene-ab-18/",
    note: "24-h-Notfallaufnahme der PUK Zürich für Erwachsene an der Lenggstrasse 31, Tel. 058 384 20 00.",
  },
  {
    id: "puk-kinder-notfall",
    type: "Schweizer Versorgung",
    short: "PUK Zürich KJPP Notfall",
    title: "Psychiatrische Universitätsklinik Zürich - Notfall für Kinder und Jugendliche",
    authors: "PUK Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "pukzh.ch",
    url: "https://www.pukzh.ch/notfall/kinder-und-jugendliche/",
    note: "24-h-Notfallversorgung für Kinder und Jugendliche, Tel. 058 384 66 66.",
  },
  {
    id: "puk-angehoerigenarbeit",
    type: "Schweizer Versorgung",
    short: "PUK Fachstelle Angehörigenarbeit",
    title: "Fachstelle Angehörigenarbeit der PUK Zürich",
    authors: "PUK Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "pukzh.ch",
    url: "https://www.pukzh.ch/sites/default/assets/File/PUK_Factsheet_Angehoerigenarbeit_05042024_final.pdf",
    note: "Vertrauliche und kostenlose Beratung für Angehörige; Kontakt: 058 384 38 00 und angehoerigenarbeit@pukzh.ch.",
  },
  {
    id: "kanton-zh-notfall",
    type: "Schweizer Versorgung",
    short: "Kanton Zürich - Notfall und Rettung",
    title: "Notfall und Rettung - Übersicht der Notrufnummern und Anlaufstellen",
    authors: "Gesundheitsdirektion Kanton Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "zh.ch",
    url: "https://www.zh.ch/de/gesundheit/notfall-rettung.html",
    note: "Offizielle Hierarchie: 144 bei Lebensgefahr, Ärztefon 0800 33 66 55 für dringliche, nicht lebensbedrohliche Lagen.",
  },
  {
    id: "opferhilfe-zh",
    type: "Schweizer Versorgung",
    short: "Opferhilfe Zürich",
    title: "Opferhilfe Zürich - 24/7-Telefon und reguläre Beratung",
    authors: "Kanton Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "zh.ch",
    url: "https://www.zh.ch/de/sicherheit-justiz/opferhilfe/opferberatung.html",
    note: "24/7-Nummer 142; reguläre Beratung 044 299 40 50 während der Bürozeiten.",
  },
  {
    id: "pro-mente-sana",
    type: "Schweizer Versorgung",
    short: "Pro Mente Sana",
    title: "Pro Mente Sana - Beratung und Information zu psychischer Gesundheit",
    authors: "Schweizerische Stiftung Pro Mente Sana",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "promentesana.ch",
    url: "https://www.promentesana.ch/",
    note: "Psychosoziale und juristische Orientierung zu psychischer Gesundheit, FU, Vorsorgeauftrag und Patientenverfügung.",
  },
  {
    id: "equilibrium",
    type: "Schweizer Versorgung",
    short: "EQUILIBRIUM / depressionen.ch",
    title: "EQUILIBRIUM - Verein zur Bewältigung von Depressionen",
    authors: "EQUILIBRIUM Schweiz",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "depressionen.ch",
    url: "https://www.depressionen.ch/",
    note: "Schweizer Selbsthilfe-Organisation für Menschen mit Depressionen und bipolaren Erkrankungen.",
  },
  {
    id: "vask",
    type: "Schweizer Versorgung",
    short: "VASK Schweiz",
    title: "VASK Schweiz - Vereinigung von Angehörigen psychisch erkrankter Menschen",
    authors: "VASK Schweiz",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "vask.ch",
    url: "https://www.vask.ch/",
    note: "Dachverband regionaler Angehörigenvereine in der Schweiz.",
  },
  {
    id: "vask-zuerich",
    type: "Schweizer Versorgung",
    short: "VASK Zürich / Stand by You Zürich",
    title: "VASK Zürich / Stand by You Zürich",
    authors: "Stand by You / VASK Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "vaskzuerich.ch",
    url: "https://vaskzuerich.ch/",
    note: "Regionale Angehörigenorganisation in Zürich; die Website verweist auf die Umbenennung zu Stand by You Zürich.",
  },
  {
    id: "selbsthilfe-zuerich",
    type: "Schweizer Versorgung",
    short: "Selbsthilfe Zürich",
    title: "Selbsthilfezentrum Region Zürich - Information, Vermittlung und Beratung",
    authors: "Selbsthilfezentrum Region Zürich",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "selbsthilfezuerich.ch",
    url: "https://www.selbsthilfezuerich.ch/shzh/de/angebot/information-vermittlung-amp-beratung.html",
    note: "Vermittlung von Selbsthilfegruppen in der Region Zürich; Kontakttelefon 043 288 88 88.",
  },
  {
    id: "selbsthilfe-schweiz",
    type: "Schweizer Versorgung",
    short: "Selbsthilfe Schweiz",
    title: "Selbsthilfe Schweiz - nationaler Dachverband",
    authors: "Selbsthilfe Schweiz",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "selbsthilfeschweiz.ch",
    url: "https://www.selbsthilfeschweiz.ch/shch/de/in-ihrer-region/selbsthilfezentren.html",
    note: "Nationaler Dachverband und regionale Vermittlung von Selbsthilfegruppen in der Schweiz.",
  },
  {
    id: "dargebotene-hand",
    type: "Schweizer Versorgung",
    short: "Dargebotene Hand 143",
    title: "Die Dargebotene Hand - 143",
    authors: "Die Dargebotene Hand",
    year: "Letzte Prüfung: 2026-04-30",
    publisher: "143.ch",
    url: "https://www.143.ch/",
    note: "Anonyme Gesprächs- und Krisenhilfe für Erwachsene, 24 Stunden täglich erreichbar.",
  },
  {
    id: "pro-juventute-147",
    type: "Schweizer Versorgung",
    short: "Pro Juventute 147",
    title: "147 - Beratung für Kinder und Jugendliche",
    authors: "Pro Juventute",
    year: "Letzte Prüfung: 2026-04-30",
    publisher: "147.ch",
    url: "https://www.147.ch/de/",
    note: "Telefon-, Chat- und SMS-Beratung für Kinder und Jugendliche, rund um die Uhr.",
  },
  {
    id: "ombudsstelle-krankenversicherung",
    type: "Schweizer Versorgung",
    short: "Ombudsstelle Krankenversicherung",
    title: "Ombudsstelle Krankenversicherung",
    authors: "Ombudsstelle Krankenversicherung",
    year: "Letzte Prüfung: 2026-05-01",
    publisher: "om-kv.ch",
    url: "https://om-kv.ch/beratung-anfordern/",
    note: "Kostenlose und unabhängige Schlichtungs- und Beratungsstelle bei Konflikten mit der Krankenversicherung.",
  },
  {
    id: "who-qualityrights",
    type: "Schweizer Versorgung",
    short: "WHO QualityRights",
    title: "WHO QualityRights - person-centred, rights-based recovery approach",
    authors: "World Health Organization",
    year: "Letzte Prüfung: 2026-04-30",
    publisher: "WHO",
    url: "https://www.who.int/teams/mental-health-and-substance-use/policy-law-rights/QualityRights",
    note: "Internationaler Rahmen für rechtebasierte und recovery-orientierte Versorgung psychischer Gesundheit.",
  },
];

const groupMeta = {
  Leitlinien: {
    title: "Leitlinien",
    blurb: "Konsentierte Empfehlungen, auf denen die Inhalte dieser Website primär beruhen.",
  },
  Klassifikation: {
    title: "Diagnostische Klassifikationen",
    blurb: "Diese Systeme sind die Grundlage für Begriffe wie Bipolar I, Bipolar II oder Zyklothymie.",
  },
  Uebersichtsarbeit: {
    title: "Übersichtsarbeiten",
    blurb: "Arbeiten, die mehrere Studien zu einem Thema zusammenfassen und einordnen.",
  },
  "Meta-Analyse": {
    title: "Meta-Analysen",
    blurb: "Quantitative Bündelungen mehrerer Studien für robustere Effektschätzungen.",
  },
  Studie: {
    title: "Primärstudien",
    blurb: "Einzelne Studien, die wir gezielt für bestimmte Aussagen, Zahlen oder Mechanismen heranziehen.",
  },
  "Schweizer Versorgung": {
    title: "Schweizer Versorgung und Anlaufstellen",
    blurb: "Regional verankerte Kontaktstellen, Notfallwege und Beratungsangebote für die Schweiz mit Schwerpunkt Kanton Zürich.",
  },
};

const groupOrder = [
  "Leitlinien",
  "Klassifikation",
  "Uebersichtsarbeit",
  "Meta-Analyse",
  "Studie",
  "Schweizer Versorgung",
];

const entries = sourceEntries.map((entry, index) => ({
  ...entry,
  number: index + 1,
  group: entry.type === "Leitlinie" ? "Leitlinien" : entry.type,
}));

const byId = Object.fromEntries(entries.map((entry) => [entry.id, entry]));

const groups = groupOrder.map((groupId) => ({
  id: groupId,
  title: groupMeta[groupId].title,
  blurb: groupMeta[groupId].blurb,
  items: entries.filter((entry) => entry.group === groupId),
})).filter((group) => group.items.length > 0);

const contactEntries = [
  {
    id: "fachstelle",
    group: "Beratung",
    label: "Fachstelle Angehörigenarbeit PUK",
    title: "Fachstelle Angehörigenarbeit PUK Zürich",
    kind: "Beratung",
    href: "tel:+41583843800",
    display: "058 384 38 00",
    url: "https://www.pukzh.ch/sites/default/assets/File/PUK_Factsheet_Angehoerigenarbeit_05042024_final.pdf",
    urlLabel: "Factsheet der Fachstelle",
    email: "angehoerigenarbeit@pukzh.ch",
    availability: "Mo-Fr nach Vereinbarung",
    description: "Vertrauliche und kostenlose Beratung für Angehörige - auch wenn die erkrankte Person nicht bei der PUK in Behandlung ist.",
    address: "Lenggstrasse 31, 8032 Zürich",
    sourceId: "puk-angehoerigenarbeit",
  },
  {
    id: "aerztefon",
    group: "Akut und 24h",
    label: "Ärztefon - Notfalldienst ZH",
    title: "Ärztefon Kanton Zürich",
    kind: "Akut",
    href: "tel:+41800336655",
    display: "0800 33 66 55",
    url: "https://www.zh.ch/de/gesundheit/notfall-rettung.html",
    urlLabel: "Notfall und Rettung im Kanton Zürich",
    availability: "24/7",
    description: "Dringliche, aber nicht lebensbedrohliche medizinische oder psychiatrische Lage im Kanton Zürich.",
    sourceId: "kanton-zh-notfall",
  },
  {
    id: "pukNotfall",
    group: "Akut und 24h",
    label: "PUK Zürich - Notfall Erwachsene",
    title: "PUK Zürich Notfall Erwachsene",
    kind: "Akut",
    href: "tel:+41583842000",
    display: "058 384 20 00",
    url: "https://www.pukzh.ch/notfall/erwachsene-ab-18/",
    urlLabel: "Notfall Erwachsene",
    availability: "24/7, ab 18 Jahren",
    description: "Psychiatrische Notfallaufnahme der PUK Zürich für Erwachsene.",
    address: "Lenggstrasse 31, 8032 Zürich",
    sourceId: "puk-zh",
  },
  {
    id: "pukKinder",
    group: "Akut und 24h",
    label: "PUK Zürich - Kinder und Jugendliche",
    title: "PUK Zürich Notfall für Kinder und Jugendliche",
    kind: "Akut",
    href: "tel:+41583846666",
    display: "058 384 66 66",
    url: "https://www.pukzh.ch/notfall/kinder-und-jugendliche/",
    urlLabel: "Notfall Kinder und Jugendliche",
    availability: "24/7",
    description: "Psychiatrische Notfallversorgung für Kinder und Jugendliche.",
    sourceId: "puk-kinder-notfall",
  },
  {
    id: "dargeboteneHand",
    group: "Akut und 24h",
    label: "Dargebotene Hand",
    title: "Die Dargebotene Hand 143",
    kind: "Akut",
    href: "tel:143",
    display: "143",
    url: "https://www.143.ch/",
    urlLabel: "143.ch",
    availability: "24/7",
    description: "Anonyme Gesprächs- und Krisenhilfe - auch für Angehörige.",
    sourceId: "dargebotene-hand",
  },
  {
    id: "opferhilfe24h",
    group: "Akut und 24h",
    label: "Opferhilfe Zürich 24 h",
    title: "Opferhilfe Zürich - 24-h-Telefon",
    kind: "Akut",
    href: "tel:142",
    display: "142",
    url: "https://www.zh.ch/de/sicherheit-justiz/opferhilfe/opferberatung.html",
    urlLabel: "Opferhilfe Zürich",
    availability: "24/7",
    description: "Anonyme und kostenlose Hilfe bei Gewalt, Bedrohung oder Stalking.",
    sourceId: "opferhilfe-zh",
  },
  {
    id: "proJuventute",
    group: "Akut und 24h",
    label: "Pro Juventute 147",
    title: "Pro Juventute 147",
    kind: "Akut",
    href: "tel:147",
    display: "147",
    url: "https://www.147.ch/de/",
    urlLabel: "147.ch",
    availability: "24/7",
    description: "Telefon-, Chat- und SMS-Beratung für Kinder und Jugendliche.",
    sourceId: "pro-juventute-147",
  },
  {
    id: "proMenteSana",
    group: "Beratung",
    label: "Pro Mente Sana",
    title: "Pro Mente Sana",
    kind: "Beratung und Recht",
    href: "tel:+41848800858",
    display: "0848 800 858",
    url: "https://www.promentesana.ch/",
    urlLabel: "promentesana.ch",
    availability: "Telefonisch zu Beratungszeiten, e-Beratung jederzeit absendbar",
    description: "Psychosoziale und juristische Beratung zu psychischer Gesundheit, FU, Vorsorgeauftrag und Patientenverfügung.",
    sourceId: "pro-mente-sana",
  },
  {
    id: "opferhilfe",
    group: "Beratung",
    label: "Opferhilfe Zürich",
    title: "Opferberatung Zürich",
    kind: "Beratung",
    href: "tel:+41442994050",
    display: "044 299 40 50",
    url: "https://www.zh.ch/de/sicherheit-justiz/opferhilfe/opferberatung.html",
    urlLabel: "Opferhilfe Zürich",
    availability: "Bürozeiten",
    description: "Vertiefte Beratung und Begleitung nach Gewalt, Bedrohung oder Stalking.",
    sourceId: "opferhilfe-zh",
  },
  {
    id: "ombudsstelleKrankenversicherung",
    group: "Beratung",
    label: "Ombudsstelle Krankenversicherung",
    title: "Ombudsstelle Krankenversicherung",
    kind: "Recht",
    href: "tel:+41412261010",
    display: "041 226 10 10",
    url: "https://om-kv.ch/beratung-anfordern/",
    urlLabel: "om-kv.ch",
    availability: "Mo-Fr 09:00-11:30",
    description: "Kostenlose und unabhängige Schlichtungsstelle bei Konflikten mit der Krankenversicherung.",
    sourceId: "ombudsstelle-krankenversicherung",
  },
  {
    id: "vask",
    group: "Selbsthilfe und Peers",
    label: "VASK Zürich",
    title: "VASK Zürich / Stand by You Zürich",
    kind: "Selbsthilfe",
    href: "tel:+41442404868",
    display: "044 240 48 68",
    url: "https://vaskzuerich.ch/",
    urlLabel: "vaskzuerich.ch",
    availability: "Infos und regionale Angebote online",
    description: "Austausch und Selbsthilfe für Angehörige psychisch erkrankter Menschen in der Region Zürich.",
    sourceId: "vask-zuerich",
  },
  {
    id: "selbsthilfe",
    group: "Selbsthilfe und Peers",
    label: "Selbsthilfe Zürich",
    title: "Selbsthilfezentrum Region Zürich",
    kind: "Vermittlung",
    href: "tel:+41432888888",
    display: "043 288 88 88",
    url: "https://www.selbsthilfezuerich.ch/shzh/de/angebot/information-vermittlung-amp-beratung.html",
    urlLabel: "selbsthilfezuerich.ch",
    availability: "Information, Vermittlung und Beratung",
    description: "Vermittelt passende Selbsthilfegruppen in der Region Zürich, auch für Angehörige.",
    sourceId: "selbsthilfe-zuerich",
  },
  {
    id: "selbsthilfeSchweiz",
    group: "Selbsthilfe und Peers",
    label: "Selbsthilfe Schweiz",
    title: "Selbsthilfe Schweiz",
    kind: "Dachverband",
    href: "tel:+41613338601",
    display: "061 333 86 01",
    url: "https://www.selbsthilfeschweiz.ch/shch/de/in-ihrer-region/selbsthilfezentren.html",
    urlLabel: "selbsthilfeschweiz.ch",
    availability: "Nationaler Dachverband",
    description: "Hilft bei der Suche nach regionalen Selbsthilfegruppen und Kontaktstellen.",
    sourceId: "selbsthilfe-schweiz",
  },
  {
    id: "equilibrium",
    group: "Selbsthilfe und Peers",
    label: "EQUILIBRIUM",
    title: "EQUILIBRIUM / depressionen.ch",
    kind: "Selbsthilfe",
    href: "tel:+41848143144",
    display: "0848 143 144",
    url: "https://www.depressionen.ch/",
    urlLabel: "depressionen.ch",
    availability: "Schweizweites Angebot",
    description: "Selbsthilfe- und Informationsangebot für Menschen mit Depressionen und bipolaren Erkrankungen, einschließlich Angehörigenangeboten.",
    sourceId: "equilibrium",
  },
];

const contacts = Object.fromEntries(contactEntries.map((contact) => [contact.id, contact]));

const contactGroupMeta = {
  "Akut und 24h": {
    title: "Akut und 24h",
    blurb: "Diese Kontakte sind für akute oder zeitkritische Lagen gedacht.",
  },
  Beratung: {
    title: "Beratung und Recht",
    blurb: "Diese Stellen helfen bei Einordnung, Fachfragen, Vorsorge und juristischen Blockaden.",
  },
  "Selbsthilfe und Peers": {
    title: "Selbsthilfe und Peers",
    blurb: "Diese Angebote helfen besonders dann, wenn Information allein nicht mehr reicht.",
  },
};

const contactGroupOrder = ["Akut und 24h", "Beratung", "Selbsthilfe und Peers"];

const contactGroups = contactGroupOrder.map((groupId) => ({
  id: groupId,
  title: contactGroupMeta[groupId].title,
  blurb: contactGroupMeta[groupId].blurb,
  items: contactEntries.filter((contact) => contact.group === groupId),
})).filter((group) => group.items.length > 0);

const telAliasMap = {
  fachstelle: "fachstelle",
  aerztefon: "aerztefon",
  pukNotfall: "pukNotfall",
  pukKinder: "pukKinder",
  proMenteSana: "proMenteSana",
  vask: "vask",
  selbsthilfe: "selbsthilfe",
  opferhilfe: "opferhilfe",
  opferhilfe24h: "opferhilfe24h",
  dargeboteneHand: "dargeboteneHand",
  proJuventute: "proJuventute",
  ombudsstelleKrankenversicherung: "ombudsstelleKrankenversicherung",
};

const tel = Object.fromEntries(
  Object.entries(telAliasMap).map(([alias, contactId]) => {
    const contact = contacts[contactId];
    return [alias, { href: contact.href, display: contact.display, label: contact.label }];
  }),
);

module.exports = {
  entries,
  byId,
  groups,
  groupOrder,
  groupMeta,
  contacts,
  contactGroups,
  contactGroupOrder,
  tel,
};
